package org.application.dbairline.model.data;

import java.sql.*;

public class DAUtility {
    private static String URL;
    private static String USER;
    private static String PASSWORD;
    private static boolean isSet = false;

    /**
     * Sets the credentials for connecting to the MySQL server with the specified URL and the given user and password.
     *
     * @param url      the URL of the database
     * @param user     the username to connect to the database
     * @param password the password to connect to the database
     * @return {@code true} if the credentials are successfully set, {@code false} otherwise
     */
    public static boolean setCredentials(String url, String user, String password) {
        if (!isSet) {
            URL = url;
            USER = user;
            PASSWORD = password;
            isSet = true;
            return true;
        }
        return false;
    }

    /**
     * Retrieves a connection to the database.
     *
     * @return the connection to the database
     * @throws SQLException if an error occurs while establishing the connection
     */
    public static Connection getConnection() throws SQLException {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    /**
     * Executes an update SQL statement using the given Connection, SQL query, and optional parameters.
     *
     * @param connection the Connection to use for executing the statement
     * @param sql        the SQL query to execute
     * @param params     the optional parameters to be used in the SQL query
     * @return the number of rows affected by the update statement
     * @throws SQLException if an error occurs while executing the statement
     */
    public static int executeUpdate(Connection connection, String sql, Object... params) throws SQLException, IllegalArgumentException {
        if (connection == null) {
            throw new SQLException("Connection object is null");
        }
        if (sql != null && !sql.trim().isEmpty() && params != null) {
            PreparedStatement queryStatement = connection.prepareStatement(sql);
            for (int i = 0; i < params.length; i++) {
                queryStatement.setObject(i + 1, params[i]);
            }
            return queryStatement.executeUpdate();

        } else {
            throw new IllegalArgumentException("Invalid SQL query or parameters provided.");
        }
    }

    /**
     * Executes a SQL query with optional parameters and returns the result set.
     *
     * @param sql    the SQL query to execute
     * @param params optional parameters to be used in the SQL query
     * @return the result set generated by the query
     * @throws SQLException if an error occurs while executing the query
     */
    public static ResultSet executeQuery(Connection connection, String sql, Object... params) throws SQLException, IllegalArgumentException {
        if (connection == null) {
            throw new SQLException("Connection object is null");
        }
        if (sql == null || sql.trim().isEmpty()) {
            throw new IllegalArgumentException("SQL query is null or empty");
        }
        if (!sql.trim().toUpperCase().startsWith("SELECT")) {
            throw new IllegalArgumentException("Query must be a SELECT query");
        }

        PreparedStatement queryStatement = connection.prepareStatement(sql);

        for (int i = 0; i < params.length; i++) {
            queryStatement.setObject(i + 1, params[i]);
        }

        return queryStatement.executeQuery();
    }
}
